### PR TITLE
Add protected term redefinition tests.

### PR DESCRIPTION
**Pull request by davidlehn**
A few of these tests look a bit crazy.  Sorry. ;-)  Suggested improvements would be welcome.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/92.html" title="Last updated on Jun 12, 2019, 5:21 PM UTC (71612ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/92/849e153...71612ae.html" title="Last updated on Jun 12, 2019, 5:21 PM UTC (71612ae)">Diff</a>

### CODE REVIEW

**Comment by dlongley** [comment]
@gkellogg,

This is related to https://github.com/w3c/json-ld-api/issues/90.

**Comment by dlongley** [comment]
@davidlehn, can you resolve the conflict?

**Comment by davidlehn** [comment]
@dlongley Fixed.

**Comment by dlongley** [comment]
@davidlehn, thanks!

**Comment by gkellogg** [comment]
@dlongley note the comment in the last commit: "Note that the algorithm sets terms to `null` in context if they're defined as `null` or `{"@id": null}` and doesn't retain the protected status, which it probably should."

If you agree, I'll update that part too.

**Comment by dlongley** [comment]
@gkellogg,

> @dlongley note the comment in the last commit: "Note that the algorithm sets terms to null in context if they're defined as null or {"@id": null} and doesn't retain the protected status, which it probably should."
> 
> If you agree, I'll update that part too.

It does seem like it should to retain protected status, i.e. what we're saying is that we'd allow for terms to be defined as null *and* protect that null definition, right? I know we have some other issue about it perhaps doing that for prefixes for security purposes.

We'd have to implement it to make sure it doesn't do anything strange or break any existing tests. We would also need new tests to check it. Have you happened to have implemented it and run it against the existing tests?

**Comment by gkellogg** [comment]
My implementation does create an empty `term definition` for either `null` or `{"@id": null}`, although it doesn't presently set `@protected` on it.

We should update step 5.4 in [IRI Expansion](https://w3c.github.io/json-ld-api/#iri-expansion) to not use a term as a Compact IRI prefix if it's _IRI mapping_ is `null`.

**Pull request merged**
