### PR TITLE
address issue #519

### PR DESCRIPTION
**Pull request by pchampin**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/520.html" title="Last updated on Jan 5, 2021, 3:50 PM UTC (d8255b1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/520/7975314...d8255b1.html" title="Last updated on Jan 5, 2021, 3:50 PM UTC (d8255b1)">Diff</a>

### CODE REVIEW

**Comment by gkellogg** [comment]
I'll review shortly, after I've had a chance to compare with my own implementation.

**Comment by gkellogg** [comment]
We should add something to the "Changes since" section to note that change, however.

**Comment by pchampin** [comment]
> We should add something to the "Changes since" section to note that change, however.

I added a bullet in "Changes since Recommendation of 16 July 2020". Is it not already the appropriate section??

**Comment by gkellogg** [comment]
> > We should add something to the "Changes since" section to note that change, however.
> 
> I added a bullet in "Changes since Recommendation of 16 July 2020". Is it not already the appropriate section??

I see it now, but I missed it when I looked before.

**Review by gkellogg — APPROVED** [review]

**Comment by gkellogg** [comment]
The updates are quite straightforward, and shouldn't have an impact on any existing conforming implementation.

**Pull request merged**
