### PR TITLE
Add implementation report for JSONLD perl module.

### PR DESCRIPTION
**Pull request by kasei**

### CODE REVIEW

**Comment by gkellogg** [comment]
You should include a soap profile for http://purl.org/NET/cpan-uri/dist/JSONLD/v_0-004. Alternatively (perhaps best), just use "my:project" for the earl:subject.

All of the tests reported for the compact-manifest seem to actually be for the expand-manifest.

When I make those changes, it runs properly with the earl-report steps described in the README. I can make those changes and run with that, but you may want to correct for the next time.

Should these results be for just Expansion and ToRdf? Or, do you do any Compaction or Framing?

**Comment by kasei** [comment]
> You should include a soap profile for http://purl.org/NET/cpan-uri/dist/JSONLD/v_0-004. Alternatively (perhaps best), just use "my:project" for the earl:subject.

What is a "soap profile"? Since the test results may change between versions, I'd prefer to keep the subject as the version. If that's possible, what needs updating to let it work with your tooling?

> All of the tests reported for the compact-manifest seem to actually be for the expand-manifest.

Oops. Fat-finger typo in my rewriting the local `file://` URLs to the actual test URIs. Will fix.

> Should these results be for just Expansion and ToRdf? Or, do you do any Compaction or Framing?

I only implement expansion and toRdf at this point.

**Comment by kasei** [comment]
Oh. "doap", obviously! 🤦‍♂️

The `homepage`, `developer`, and `programming-language` properties all have a domain of `Project`, so I'm not sure I can assert them on a `Version`. Thoughts?

**Comment by gkellogg** [comment]
If you make the version a doap:Project it will likely work okay, but you may need to jar the version a version of itself, because of the query.

**Comment by kasei** [comment]
A cursory glance at earl-report looks like it's based on SPARQL queries. Couldn't a query easily allow for the `subject` to be either a Project or a Version? e.g.

```sparql
SELECT ?subject ?test ?status WHERE {
	?proj a doap:Project ;
		doap:homepage ?homepage ;
		doap:programming-language ?lang .
	?proj (doap:release)? ?subject .
	
	[] a earl:Assertion;
		earl:result [
			earl:outcome ?status
		] ;
		earl:subject ?subject ;
		earl:test ?test .
}
```

**Comment by kasei** [comment]
The `Version` isn't a `Project`, though. The domain/range of `doap:release` are clear here. Also, doap asserts that `doap:homepage` is an IFPs, so it can't be shared between the project and its versions.

**Comment by gkellogg** [comment]
> A cursory glance at earl-report looks like it's based on SPARQL queries. Couldn't a query easily allow for the `subject` to be either a Project or a Version? e.g.
> 
> ```sparql
> SELECT ?subject ?test ?status WHERE {
> 	?proj a doap:Project ;
> 		doap:homepage ?homepage ;
> 		doap:programming-language ?lang .
> 	?proj (doap:release)? ?subject .
> 	
> 	[] a earl:Assertion;
> 		earl:result [
> 			earl:outcome ?status
> 		] ;
> 		earl:subject ?subject ;
> 		earl:test ?test .
> }
> ```

In a future release of earl-report I can open it up to allow a doap:Version to be used as `?subject`, but for the time being,, please using the doap:Project as the test subject.

I'll go ahead and integrate your results with that change.

**Comment by gkellogg** [comment]
One suggestion, the name "JSONLD" for the project is a bit generic, at least for the purposes of the report. You might consider a somewhat more unique name.

if you look at the [integrated report](https://w3c.github.io/json-ld-api/reports/), other projects have names that are slightly more associated with their specific implementation.

**Comment by davidlehn** [comment]
@gkellogg The test subjects have a "Programming Language" field.  Perhaps that should be added as a row in the tables just to be explicit.  Would also help with names like "JSON::LD". :-)

**Comment by gkellogg** [comment]
Touché. I can make that happen.

**Pull request merged**
