### PR TITLE
Test suite ported from json-ld.org.

### PR DESCRIPTION
**Pull request by gkellogg**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/11.html" title="Last updated on Jul 24, 2018, 9:23 PM GMT (5c10380)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/11/466065d...5c10380.html" title="Last updated on Jul 24, 2018, 9:23 PM GMT (5c10380)">Diff</a>

### CODE REVIEW

**Comment by davidlehn** [comment]
I'm guessing the .htaccess file here won't work.  What's the plan for parts that use those features?

**Comment by gkellogg** [comment]
If we sync it to w3.org and update the expected base IRIs in some cases, it would work. Just keeping it there to preserve for now.

**Comment by davidlehn** [comment]
If we're moving all these files, might be a good time to consider using subdirs.  Tools like github are not so great at handling a 1000s+ files per dir.

**Comment by gkellogg** [comment]
> If we're moving all these files, might be a good time to consider using subdirs. Tools like github are not so great at handling a 1000s+ files per dir.

Sure, easy enough, I'll take care of it.

**Pull request merged**
