### PR TITLE
Timothee updates

### LINKED ISSUE #475: Create Term Definition algorithm, possible imprecision step 11
Step 11 of the [Create Term Definition Algorithm](https://www.w3.org/TR/json-ld11-api/#create-term-definition), it is said that
> If the `@protected` entry in `value` is `true` set the `protected` flag in `definition` to `true`

Strictly following this, a `"@protected": false` in a term definition is ignored.
However, this makes the [expansion test `pr13`](https://w3c.github.io/json-ld-api/tests/expand/pr13-in.jsonld) to fail.

### LINKED ISSUE #477: Expansion Algorithm confusing Step 13.8.3.7.2.3 not covered by the expansion tests
In the [Expansion Algorithm](https://www.w3.org/TR/json-ld11-api/#expansion-algorithm) I personally find the description of the Step 13.8.3.7.2.3 hard to understand:
> Initialize `index property values` to the concatenation of `re-expanded index`
with any existing values of `expanded index key` in `item`.

The variable `re-expanded index` holds a value object. I don't understand how to "concatenate" a value object with anything. I find the use of "any" confusing, does it mean "all", or "the first one you find"? Moreover, `expanded index key` is most likely to be an expanded IRI and I don't see any situation where it would appear in `item` (unless we consider the expanded keys in `item`? I'm lost).

In my implementation, I temporarily simplified this step by just defining `index property values` as `re-expanded index`. My plan was to come back to it while running the expansion tests, trying to understand reading the tests.

However I now pass all the tests without changing this part...

### LINKED ISSUE #478: What is the purpose of `from map` in the Expansion Algorithm?
The Expansion Algorithm requires a boolean `from map` variable as input. Its value is never changed across the expansion algorithms and is always set to `false`. There are only 3 occurrences of this variable in the whole API document. It doesn't seem to be used.

### LINKED ISSUE #479: Expansion Algorithm, possible imprecision step 13.4.6.2
While expanding `@included` step 13.4.6.2 it is said
> Set expanded value to the result of using this algorithm recursively passing active context, active property, value for element, base URL, and the frameExpansion and ordered flags, ensuring that the result is an array.

I believe the implementation is supposed to pass `@included` as active property instead of passing the current value. Otherwise, free floating literals inside the included block are automatically dropped, which makes the test [`expand/in07`](https://w3c.github.io/json-ld-api/tests/expand/in07-in.jsonld) to fail.

### PR DESCRIPTION
**Pull request by gkellogg**
* Add note that unordered arrays may contain duplicate values after expansion. For #473. Other parts of #473 are deferred.
* Updated step 11 of the Create Term Definition algorithm to use any boolean value of `@protected`, not just `true`. Fixes #475.
* Improve wording of expansion 13.8.3.7.2.3. Fixes #477.
* Update step 13.8.3.6 of the Expansion algorithm to pass `true` for the from map parameter to properly manage reverting active contexts. Fixes #478.
* Update step 13.4.6.2 of the Expansion algorithm to pass `null` for active property, as included blocks do not define a relationship to a referencing node. Fixes #479.
* Mark expand/0122 non-normative, as it results in an invalid JSON-LD result. Note: toRdf/e122 does not include a triple for this, so it remains normative. For #480.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/481.html" title="Last updated on Apr 27, 2020, 6:52 PM UTC (9bc2f71)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/481/c512a0d...9bc2f71.html" title="Last updated on Apr 27, 2020, 6:52 PM UTC (9bc2f71)">Diff</a>

### CODE REVIEW

**Comment by gkellogg** [comment]
@iherman note that this updates the implementation report which now considers expand/0122 to be non-normative, as the resulting file is not legal JSON-LD.

**Comment by gkellogg** [comment]
@iherman So, does that mean you'd like to back out the change that affects the implementation report, or just be sure it's in prior to acceptance?

**Comment by gkellogg** [comment]
@iherman: we have agreement on everything, we can pull this PR pending your clarification to changing the implementation report to show the affected test as being non-normative. If you don't want this change, I can back out the commit.

**Comment by iherman** [comment]
@gkellogg I am less worried about the implementation report, as long as it does not change our exit criteria results:-). We did agree (and I told the Director) that we intend to add new implementations, for example, to the report. I am worried about the specifications themselves.

I intend to set up the errata page/script for all documents this week. We should begin to use that if needed...

**Comment by gkellogg** [comment]
> @gkellogg I am less worried about the implementation report, as long as it does not change our exit criteria results:-). We did agree (and I told the Director) that we intend to add new implementations, for example, to the report. I am worried about the specifications themselves.

IIRC, we agreed to make these changes to the spec, are you saying we shouldn’t pull the PR now? I’m confused.

**Comment by iherman** [comment]
>> @gkellogg I am less worried about the implementation report, as long as it does not change our exit criteria results:-). We did agree (and I told the Director) that we intend to add new implementations, for example, to the report. I am worried about the specifications themselves.
>
> IIRC, we agreed to make these changes to the spec, are you saying we shouldn’t pull the PR now? I’m confused.

We are talking one another... reset:-) What I mean is:

- merge this PR, meaning the report as well as the spec gets a minor update
- no more PR-s on the spec
- PR-s on the report are o.k. for the future, too.

I am afraid we are in a violent agreement...

**Comment by gkellogg** [comment]
Okay, thanks!

**Pull request merged**
